# Do NOT update manually; changes here will be overwritten by Copier
_commit: 5a39237
_src_path: https://github.com/grap/oca-addons-repo-template-new.git
ci: GitHub
dependency_installation_mode: PIP
generate_requirements_txt: true
github_check_license: true
github_ci_extra_env: {}
github_enable_codecov: true
github_enable_makepot: false
github_enable_stale_action: false
github_enforce_dev_status_compatibility: false
include_wkhtmltopdf: false
odoo_real_version: 12.0
odoo_version: 16.0
org_name: GRAP
org_slug: grap
rebel_module_groups: []
repo_description: ' The ``company_wizard_base`` create a new menu item that provide
    a wizard to create a new company.

    Then, all the other modules are glue module, to handle extra settings required
    when other modules are installed. '
repo_name: Odoo modules that provide a wizard to create companies
repo_slug: odoo-addons-company-wizard
repo_website: https://github.com/grap/odoo-addons-company-wizard
travis_apt_packages: []
travis_apt_sources: []

